"""Export routes -- extracted from main.py for maintainability."""
from fastapi import APIRouter, Query, Request
from fastapi.responses import JSONResponse, Response
import re

router = APIRouter(prefix="/api", tags=["export"])


# [v8.0] Deduplicated: /api/export/md is handled by kb.py (registered first)
# export.py provides the url-based variant at /api/v3/export/md
@router.get("/v3/export/md")
async def export_markdown_by_url(url: str = Query(...)):
    """Export video transcript as Markdown, by B站 URL."""
    from bilibili_client import extract_bvid, get_video_info, get_full_subtitle
    try:
        bvid = extract_bvid(url)
        info = await get_video_info(bvid)
        sub = await get_full_subtitle(bvid)
        if sub.body:
            lines = ["- [{:02d}:{:02d}] {}".format(
                int(x.from_ // 60), int(x.from_ % 60), x.content
            ) for x in sub.body]
            md = (
                "# " + info.title + "\n\n"
                "> Author: " + info.owner_name + " | BV: " + bvid + "\n\n"
                "## Transcript\n\n"
                + "\n".join(lines) + "\n\n---\n"
                "*Generated by BiliSum*"
            )
        else:
            md = "# " + info.title + "\n\n> No subtitle available\n"
        safe_filename = re.sub(r'[\\/:*?"<>|]', '_', bvid)
        return Response(
            content=md, media_type="text/markdown; charset=utf-8",
            headers={"Content-Disposition": "attachment; filename=" + safe_filename + "_transcript.md"}
        )
    except Exception as e:
        return JSONResponse({"success": False, "error": str(e)})


@router.post("/export/docx")
async def export_docx(request: Request):
    """Export video summary to .docx (Word document with CJK font support)."""
    from docx_exporter import generate_docx
    try:
        body = await request.json()
        bvid = body.get("bvid", "")
        title = body.get("title", bvid)
        author = body.get("author", "")
        summary = body.get("summary", "")
        transcript = body.get("transcript", "")
        tags = body.get("tags", [])
        if not bvid:
            return JSONResponse({"success": False, "error": "Missing bvid"})

        # Fetch subtitle data for chapter extraction and timestamped transcript
        chapters = None
        try:
            from bilibili_client import get_full_subtitle
            sub = await get_full_subtitle(bvid)
            if sub.body:
                # Rebuild timestamped transcript from structured subtitle data
                # (frontend sends sub.text which is space-joined without timestamps)
                ts_lines = []
                for x in sub.body:
                    m, s = divmod(int(x.from_), 60)
                    ts_lines.append(f"[{m:02d}:{s:02d}] {x.content}")
                transcript = "\n".join(ts_lines)

                # Extract chapter boundaries (every ~5 minutes where subtitle starts a new segment)
                chapters = []
                for i, x in enumerate(sub.body):
                    if (x.from_ % 300) < 15 and i > 0:
                        chapters.append({
                            "from": x.from_,
                            "to": x.to,
                            "title": x.content[:40]
                        })
        except Exception:
            pass  # chapters are optional — proceed without on any error

        docx_bytes = generate_docx(title, bvid, author, summary, transcript, tags, chapters=chapters)
        safe_name = re.sub(r'[\\/:*?"<>|]', '_', bvid)
        return Response(
            content=docx_bytes,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f"attachment; filename={safe_name}_summary.docx"}
        )
    except Exception as e:
        return JSONResponse({"success": False, "error": str(e)})



